apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: taskmanager
    tier: backend
spec:
  selector:
    app: taskmanager
    tier: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

