apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: taskmanager
    tier: db
spec:
  selector:
    app: taskmanager
    tier: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP

